icons = {
"social": ["social", "social.png", 250, 0],
"family": ["family", "family.png", 280, 530],
"children": ["children", "children.png", 280, 720],
"partnership": ["partnership", "partnership.png", 30, 350],
"friends": ["friends", "friends.png", 285, 170],
"pets": ["pets", "pets.png", 100, 50],
"leisure": ["leisure", "leisure.png", 100, 50],
"travelling": ["travelling", "travelling.png", 100, 50],
"fitness_and_sport": ["fitness_and_sport", "fitness and sport.png", 100, 50],
"diet": ["diet", "diet.png", 100, 50],
"health" : ["health" , "health.png", 100, 50],
"work_life_balance": ["work_life_balance", "work-life-balance.png", 100, 50],
"wealth": ["wealth", "wealth.png", 100, 50],
"financial_independence": ["financial_independence", "financial independence.png", 100, 50],
"knowledge_and_education": ["knowledge_and_education", "knowledge and education.png", 100, 50],
"expert": ["expert", "expert.png", 100, 50],
"leadership": ["leadership", "leadership.png", 100, 50],
"sustainability": ["sustainability", "sustainability.png", 210, 90],
"ethics": ["ethics", "ethics.png", 100, 50],
"generous": ["generous", "generous.png", 100, 50],
"fairness": ["fairness", "fairness.png", 100, 50],
"equality": ["equality", "equality.png", 100, 50],
"conflict_resolution": ["conflict_resolution", "conflict resolution.png", 100, 50],
"open_minded": ["open_minded", "open-minded.png", 100, 50],
"self_driven": ["self_driven", "self-driven.png", 100, 50],
"independence": ["independence", "independence.png", 100, 50],
"religion": ["religion", "religion.png", 100, 50],
"meditation": ["meditation", "meditation.png", 100, 50],
"mindfulness": ["mindfulness", "mindfulness.png", 100, 50],
"poverty": ["poverty", "poverty.png", 200, 620],
"unemployment": ["unemployment", "unemployment.png", 200, 750],
"loneliness": ["loneliness", "loneliness.png", 350, 50],
"conflict": ["conflict", "conflict.png", 420, 520],
"adventure": ["adventure", "adventure.png", 150, 20],
"power": ["power", "power.png", 380, 200]
}