icons = {
"social": "social.png",
"family": "family.png",
"children": "children.png",
"partnership": "partnership.png",
"friends": "friends.png",
"pets": "pets.png",
"leisure": "leisure.png",
"travelling": "travelling.png",
"fitness and sport": "fitness and sport.png",
"diet": "diet.png",
"health ": "health.png",
"work-life-balance": "work-life-balance.png",
"wealth": "wealth.png",
"financial independence": "financial independence.png",
"knowledge and education": "knowledge and education.png",
"expert": "expert.png",
"leadership": "leadership.png",
"sustainability": "sustainability.png",
"ethics": "ethics.png",
"generous": "generous.png",
"fairness": "fairness.png",
"equality": "equality.png",
"conflict resolution": "conflict resolution.png",
"open-minded": "open-minded.png",
"self-driven": "self-driven.png",
"independence": "independence.png",
"religion": "religion.png",
"meditation": "meditation.png",
"mindfulness": "mindfulness.png",
"poverty": "poverty.png",
"unemployment": "unemployment.png",
"loneliness": "loneliness.png",
"conflict": "conflict.png",
"adventure": "adventure.png",
"power": "power.png"
}