icons = {
"social": ["social", "social.png", 250, 0],
"family": ["family", "family.png", 280, 530],
"children": ["children", "children.png", 280, 720],
"partnership": ["partnership", "partnership.png", 30, 320],
"friends": ["friends", "friends.png", 285, 170],
"pets": ["pets", "pets.png", 80, 70],
"leisure": ["leisure", "leisure.png", 60, 400],
"travelling": ["travelling", "travelling.png", 60, 650],
"fitness_and_sport": ["fitness_and_sport", "fitness and sport.png", 400, 580],
"diet": ["diet", "diet.png", 40, 200],
"health" : ["health" , "health.png", 320, 0],
"work_life_balance": ["work_life_balance", "work-life-balance.png", 380, 155],
"wealth": ["wealth", "wealth.png", 130, 150],
"financial_independence": ["financial_independence", "financial independence.png", 240, 830],
"knowledge_and_education": ["knowledge_and_education", "knowledge and education.png", 150, 390],
"expert": ["expert", "expert.png", 320, 870],
"leadership": ["leadership", "leadership.png", 380, 770],
"sustainability": ["sustainability", "sustainability.png", 210, 90],
"ethics": ["ethics", "ethics.png", 100, 270],
"generous": ["generous", "generous.png", 50, 480],
"fairness": ["fairness", "fairness.png", 420, 320],
"equality": ["equality", "equality.png", 390, 670],
"conflict_resolution": ["conflict_resolution", "conflict resolution.png", 140, 480],
"open_minded": ["open_minded", "open_minded.png", 125, 710],
"self_driven": ["self_driven", "self_driven.png", 190, 220],
"independence": ["independence", "independence.png", 130, 620],
"religion": ["religion", "religion.png", 260, 290],
"meditation": ["meditation", "meditation.png", 230, 410],
"mindfulness": ["mindfulness", "mindfulness.png", 40, 560],
"poverty": ["poverty", "poverty.png", 220, 620],
"unemployment": ["unemployment", "unemployment.png", 200, 750],
"loneliness": ["loneliness", "loneliness.png", 350, 70],
"conflict": ["conflict", "conflict.png", 440, 500],
"adventure": ["adventure", "adventure.png", 150, 20],
"power": ["power", "power.png", 380, 230]
}