

woman30 = [
    "I know that one thing I could do better is to manage my time more efficiently. There are days when I feel overwhelmed and struggle to balance my personal and professional responsibilities. I need to work on prioritizing my tasks and delegating when possible to avoid burnout and ensure that I'm making the most of my time.",
    "There are so many things that I want to learn about in order to broaden my perspective and deepen my understanding of the world. One area that I'm particularly interested in is learning more about different cultures and their customs. I also want to explore new subjects like philosophy and psychology, which I believe will help me to become a more well-rounded individual.",
    "I want to improve my daily habits so that I can live a healthier and more fulfilling life. This means making small changes like getting more exercise, eating a balanced diet, and practicing mindfulness. By making these habits a regular part of my routine, I know that I'll be able to improve my overall well-being and achieve my goals.",
    "In the future, I want to have a fulfilling social life that's filled with meaningful connections and experiences. This means surrounding myself with people who share my values and interests, and making time for fun activities like travel and trying new restaurants. I want to prioritize my relationships and create a community of like-minded individuals who support and inspire me.",
    "In the future, I want to continue pursuing my hobbies and interests, like reading, hiking, and painting. I believe that these activities are important for my personal growth and happiness, and I want to make sure that I'm always making time for them.",
    "Family is important to me, and I want to make sure that I'm building strong and supportive relationships with my loved ones. In the future, I hope to have a happy and healthy family life, filled with love, laughter, and cherished memories.",
    "In the future, I want to have a successful and fulfilling career that allows me to make a positive impact on the world. I hope to continue working in the field of data science, taking on leadership roles and tackling challenging projects that push me to grow and learn.",
    "There are many qualities that I admire in others, like kindness, resilience, and creativity. I strive to embody these qualities in my own life, and I believe that by doing so, I can make a positive impact on the world.",
    "My ideal future is one where I'm surrounded by love, happiness, and fulfillment. I hope to have a successful career, a supportive community, and a happy family life. I want to continue learning and growing as a person, and making a positive impact on the world.",
    "The future I want to avoid is one where I'm unfulfilled and unhappy. I don't want to settle for a career or lifestyle that doesn't bring me joy, and I don't want to surround myself with people who bring me down. I want to avoid a future where I'm stuck in a rut and not living up to my full potential."
]

transgender_woman20 = [
    "One thing I could do better is to improve my communication skills. Sometimes I struggle to express my thoughts and ideas clearly, which can lead to misunderstandings and missed opportunities. By working on my communication skills, I can better convey my message and connect with others on a deeper level.",
    "There are so many things I want to learn about, but at the top of my list is improving my knowledge about environmental sustainability. I want to better understand how I can reduce my impact on the environment and live a more eco-friendly lifestyle.",
    "I want to improve my daily exercise routine and make it a consistent habit. I know that physical activity is important for my health and wellbeing, but sometimes I struggle to find the motivation to get moving. By making exercise a regular part of my routine, I can improve my physical and mental health.",
    "In the future, I hope to have a strong and supportive social network of friends and family. I want to cultivate deep and meaningful relationships with the people in my life and create lasting memories together.",
    "In the future, I hope to spend more time exploring the great outdoors and going on adventures. I want to challenge myself physically and mentally by trying new activities and pushing myself out of my comfort zone.",
    "In the future, I hope to have a happy and loving family with my partner and children. I want to create a warm and nurturing home environment where everyone feels loved and supported.",
    "In the future, I hope to have a fulfilling and meaningful career where I can make a positive impact on the world. I want to use my skills and talents to help others and create a better future for all.",
    "I admire people who are kind, empathetic, and compassionate. These qualities are essential for building strong and supportive relationships and creating a better world for everyone.",
    "In my ideal future, I am living a happy and fulfilling life surrounded by people I love and doing work that I find meaningful and impactful. I am healthy, financially secure, and contributing to the betterment of society.",
    "A future to avoid would be one where I am stuck in a job or lifestyle that makes me unhappy and unfulfilled. I want to avoid a future where I am not living up to my full potential or making a positive impact on the world."
]

woman40 = [
    "I would like to take more risks. As I get older, I find myself becoming more cautious and hesitant to try new things. But I know that growth and progress often come from stepping outside of our comfort zones. So I am working on cultivating a mindset of courage and openness to new experiences. I am reminding myself that failure is not the end of the world, and that taking a chance can lead to great rewards.",
    "I want to learn more about sustainable design practices and how I can integrate them into my work. By being mindful of my environmental impact, I can create designs that are both beautiful and responsible.",
    "I want to improve my habit of procrastination by setting more concrete goals and deadlines for myself. By breaking down large tasks into smaller, more manageable steps, I can make steady progress towards my goals and avoid getting overwhelmed.",
    "In the future, I want to maintain close relationships with my family and friends while also expanding my social circle through networking events and professional organizations. I believe that having a strong support network is essential for personal and professional success.",
    "In my leisure time, I want to take up hiking and explore more of the natural beauty around me. I find that being in nature helps me to recharge and gain perspective, and I want to make this a regular part of my self-care routine.",
    "In the future, I see myself as a proud grandparent, surrounded by a loving and supportive family. Family is important to me, and I want to continue to nurture these relationships as I age.",
    "In the future, I see myself as a respected and influential figure in the design world, with a thriving business and a team of talented collaborators. I want to continue to push the boundaries of what is possible in design and inspire others to do the same.",
    "I admire people who are resilient, compassionate, and self-motivated. These qualities inspire me to be a better person and strive towards my goals, even in the face of adversity.",
    "In my ideal future, I am still working as a graphic designer, but I have expanded my business to include more clients and larger projects. I have a strong network of colleagues and collaborators who inspire me and challenge me to grow. I am healthy, active, and surrounded by loved ones who support and uplift me. And I am making a positive impact on the world through my work and my relationships.",
    "A future that I want to avoid is one where I am stagnant, complacent, and disengaged from the world around me. I want to continue to learn, grow, and contribute in meaningful ways for as long as I am able. I want to live a life that is full of purpose and meaning, and that makes a positive difference in the world."
]
